# Generated by Django 6.0.6 on 2026-06-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App')], max_length=20),
        ),
    ]
