# Generated by Django 6.0.6 on 2026-06-29 15:52

import apps.notifications.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_orderitem_order_order_user_placed_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=apps.notifications.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_template', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event_type', 'channel', 'version'), name='unique_template_version')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=apps.notifications.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App')], max_length=20)),
                ('event_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], default='pending', max_length=20)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_created_at_idx'), models.Index(fields=['status', 'last_attempted_at'], name='status_attempt_idx'), models.Index(fields=['status'], name='notification_status_idx'), models.Index(fields=['order'], name='notification_order_idx'), models.Index(fields=['event_type'], name='event_type_idx')],
            },
        ),
    ]
