# Generated by Django 6.0.6 on 2026-07-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
