# Generated by Django 6.0.6 on 2026-07-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('ORDER_CANCELLED', 'Order Cancelled'), ('ORDER_SHIPPED', 'Order Shipped'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('ORDER_CANCELLED', 'Order Cancelled'), ('ORDER_SHIPPED', 'Order Shipped'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed')], max_length=64),
        ),
    ]
