# Generated by Django 6.0.6 on 2026-07-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed'), ('deferred', 'Deferred')], default='pending', max_length=20),
        ),
    ]
