# Generated by Django 6.0.6 on 2026-08-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('ORDER_CANCELLED', 'Order Cancelled'), ('ORDER_SHIPPED', 'Order Shipped'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('TEST_NOTIFICATION', 'Test Notification')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('ORDER_CANCELLED', 'Order Cancelled'), ('ORDER_SHIPPED', 'Order Shipped'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('TEST_NOTIFICATION', 'Test Notification')], max_length=64),
        ),
    ]
