# Generated by Django 6.0.6 on 2026-08-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
