# Generated by Django 6.0.6 on 2026-08-30 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_notification_error_message'),
        ('orders', '0002_order_orderitem_order_order_user_placed_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_for'], name='scheduled_for_idx'),
        ),
    ]
