# Generated by Django 6.0.6 on 2026-08-30 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_notification_scheduled_for_idx'),
        ('orders', '0002_order_orderitem_order_order_user_placed_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='scheduled_for_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'scheduled_for'], name='status_scheduled_for_idx'),
        ),
    ]
