# Generated by Django 6.0.6 on 2026-09-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_remove_notification_scheduled_for_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('ORDER_CANCELLED', 'Order Cancelled'), ('ORDER_SHIPPED', 'Order Shipped'), ('ORDER_DELIVERED', 'Order Delivered'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('TEST_NOTIFICATION', 'Test Notification')], max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('ORDER_CREATED', 'Order Created'), ('ORDER_CANCELLED', 'Order Cancelled'), ('ORDER_SHIPPED', 'Order Shipped'), ('ORDER_DELIVERED', 'Order Delivered'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('TEST_NOTIFICATION', 'Test Notification')], max_length=64),
        ),
    ]
