# Generated by Django 6.0.6 on 2026-10-07 14:36

from django.db import migrations

def create_notification_templates(apps, schema_editor):
    NotificationTemplate = apps.get_model(
        "notifications",
        "NotificationTemplate",
    )

    templates = [
        # ORDER_CREATED
        {
            "event_type": "ORDER_CREATED",
            "channel": "EMAIL",
            "subject": "Order Confirmed — {{ order_id }}",
            "body_template": """Hello {{ metadata.shipping_address.name }},

Your order has been successfully placed.

Order ID: {{ order_id }}
Status: {{ order_status }}
Total Amount: {{ total_amount }}

Shipping Address:
{{ metadata.shipping_address.name }}
{{ metadata.shipping_address.line1 }}
{{ metadata.shipping_address.line2 }}
{{ metadata.shipping_address.city }}, {{ metadata.shipping_address.state }}
{{ metadata.shipping_address.country }} - {{ metadata.shipping_address.postal_code }}

{% if metadata.notes %}
Delivery Notes: {{ metadata.notes }}
{% endif %}

Thank you for your order.""",
        },
        {
            "event_type": "ORDER_CREATED",
            "channel": "SMS",
            "subject": "",
            "body_template": (
                "Your order {{ order_id }} has been placed successfully. "
                "Total: {{ total_amount }}. Status: {{ order_status }}."
            ),
        },
        {
            "event_type": "ORDER_CREATED",
            "channel": "IN_APP",
            "subject": "Order Confirmed",
            "body_template": (
                "Your order {{ order_id }} has been placed successfully. "
                "Total: {{ total_amount }}."
            ),
        },

        # ORDER_CANCELLED
        {
            "event_type": "ORDER_CANCELLED",
            "channel": "EMAIL",
            "subject": "Order Cancelled — {{ order_id }}",
            "body_template": """Hello {{ metadata.shipping_address.name }},

Your order has been cancelled.

Order ID: {{ order_id }}
Status: {{ order_status }}
Order Amount: {{ total_amount }}

If you did not request this cancellation or have any questions, please contact support.

Regards,
Notification Service""",
        },
        {
            "event_type": "ORDER_CANCELLED",
            "channel": "SMS",
            "subject": "",
            "body_template": (
                "Your order {{ order_id }} has been cancelled. "
                "Order amount: {{ total_amount }}."
            ),
        },
        {
            "event_type": "ORDER_CANCELLED",
            "channel": "IN_APP",
            "subject": "Order Cancelled",
            "body_template": (
                "Your order {{ order_id }} has been cancelled."
            ),
        },

        # ORDER_SHIPPED
        {
            "event_type": "ORDER_SHIPPED",
            "channel": "EMAIL",
            "subject": "Your Order Has Shipped — {{ order_id }}",
            "body_template": """Hello {{ metadata.shipping_address.name }},

Good news! Your order has been shipped.

Order ID: {{ order_id }}
Status: {{ order_status }}
Total Amount: {{ total_amount }}

Shipping Address:
{{ metadata.shipping_address.name }}
{{ metadata.shipping_address.line1 }}
{{ metadata.shipping_address.line2 }}
{{ metadata.shipping_address.city }}, {{ metadata.shipping_address.state }}
{{ metadata.shipping_address.country }} - {{ metadata.shipping_address.postal_code }}

Your order is now on its way.

Regards,
Notification Service""",
        },
        {
            "event_type": "ORDER_SHIPPED",
            "channel": "SMS",
            "subject": "",
            "body_template": (
                "Your order {{ order_id }} has been shipped and is on its way. "
                "Status: {{ order_status }}."
            ),
        },
        {
            "event_type": "ORDER_SHIPPED",
            "channel": "IN_APP",
            "subject": "Order Shipped",
            "body_template": (
                "Your order {{ order_id }} has been shipped and is on its way."
            ),
        },

        # ORDER_DELIVERED
        {
            "event_type": "ORDER_DELIVERED",
            "channel": "EMAIL",
            "subject": "Order Delivered — {{ order_id }}",
            "body_template": """Hello {{ metadata.shipping_address.name }},

Your order has been delivered successfully.

Order ID: {{ order_id }}
Status: {{ order_status }}
Total Amount: {{ total_amount }}

We hope you enjoy your purchase.

Thank you for shopping with us.

Regards,
Notification Service""",
        },
        {
            "event_type": "ORDER_DELIVERED",
            "channel": "SMS",
            "subject": "",
            "body_template": (
                "Your order {{ order_id }} has been delivered successfully. "
                "Thank you for shopping with us."
            ),
        },
        {
            "event_type": "ORDER_DELIVERED",
            "channel": "IN_APP",
            "subject": "Order Delivered",
            "body_template": (
                "Your order {{ order_id }} has been delivered successfully."
            ),
        },
    ]

    for template in templates:
        NotificationTemplate.objects.get_or_create(
            event_type=template["event_type"],
            channel=template["channel"],
            version=1,
            defaults={
                "subject": template["subject"],
                "body_template": template["body_template"],
                "is_active": True,
            },
        )

def remove_notification_templates(apps, schema_editor):
    NotificationTemplate = apps.get_model(
        "notifications",
        "NotificationTemplate",
    )

    order_event_types = [
        "ORDER_CREATED",
        "ORDER_CANCELLED",
        "ORDER_SHIPPED",
        "ORDER_DELIVERED",
    ]

    NotificationTemplate.objects.filter(
        event_type__in=order_event_types,
        channel__in=["EMAIL", "SMS", "IN_APP"],
        version=1,
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_alter_notification_event_type_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_notification_templates,
            remove_notification_templates,
        )
    ]
